// generated by scripts/fuzz_mangle.mjs — do not edit
let callBudget = 12;
const trace: number[] = [];
let a = 100, b = 10, c = 0, x = 1, y = 2, z = 3;
const obj: Record<string, number> = { p: 0, q: 1, r: 2 };
const arr = [0, 1, 2];
const bag = { alpha: 1, beta: 2, gamma: 3 };
const keys = ['alpha', 'beta'];
const dynamicKey = keys[arr[0]];
class C0 {
  #secret = 7;
}
;
console.log([
  new C0()
]);
