// generated by scripts/fuzz_mangle.mjs — do not edit
let callBudget = 12;
const trace: number[] = [];
let a = 100, b = 10, c = 0, x = 1, y = 2, z = 3;
const obj: Record<string, number> = { p: 0, q: 1, r: 2 };
const arr = [0, 1, 2];
const bag = { alpha: 1, beta: 2, gamma: 3 };
const keys = ['alpha', 'beta'];
const dynamicKey = keys[arr[0]];
for (let brake4 = 4; brake4-- > 0 && (obj); ) {
  {
    for (let brake5 = 4; brake5-- > 0 && (`k${(bag.alpha ? bag.alpha : obj.r)}`); ) {
      (obj['q'] = { ...bag, g7: arr[2] });
    }
  }
}
console.log([
  obj
]);
