#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "$0")/.." && pwd)"
cd "$repo_root"

report_root="_build/bridge-quality"
log_root="$report_root/logs"
report_file="$report_root/REPORT.md"

rm -rf "$report_root"
mkdir -p "$log_root"

checks=()
statuses=()
logs=()

run_check() {
  local name="$1"
  shift
  local log_file="$log_root/$name.log"

  checks+=("$name")
  logs+=("$log_file")
  if "$@" > "$log_file" 2>&1; then
    statuses+=("pass")
  else
    statuses+=("fail")
  fi
}

count_files() {
  local root="$1"
  local pattern="$2"

  if [ ! -d "$root" ]; then
    printf '0\n'
    return
  fi
  find "$root" -path "$report_root" -prune -o -type f -name "$pattern" -print | wc -l | tr -d ' '
}

sum_lines() {
  local root="$1"
  local name_pattern="$2"

  if [ ! -d "$root" ]; then
    printf '0\n'
    return
  fi
  local total=0
  local file
  while IFS= read -r file; do
    total=$((total + $(wc -l < "$file")))
  done < <(find "$root" -path "$report_root" -prune -o -type f -name "$name_pattern" -print)
  printf '%s\n' "$total"
}

count_matching_files() {
  local root="$1"
  local name_pattern="$2"
  local pattern="$3"

  if [ ! -d "$root" ]; then
    printf '0\n'
    return
  fi
  local total=0
  local file
  local count
  while IFS= read -r file; do
    count="$(grep -E -c "$pattern" "$file" 2>/dev/null || true)"
    total=$((total + count))
  done < <(find "$root" -path "$report_root" -prune -o -type f -name "$name_pattern" -print)
  printf '%s\n' "$total"
}

run_check "verify-scaffolds" bash scripts/verify_scaffolds.sh
run_check "verify-generated-fixtures" bash scripts/verify_generated_fixtures.sh
run_check "verify-examples" bash scripts/verify_examples.sh

moonbit_bridge_files="$(count_files _build 'bridge.mbt')"
moonbit_decl_files="$(count_files _build 'bridge.mbti')"
typescript_decl_files="$(count_files _build '*.d.ts')"
javascript_files="$(count_files _build '*.js')"
moonbit_bridge_lines="$(sum_lines _build 'bridge.mbt')"
moonbit_decl_lines="$(sum_lines _build 'bridge.mbti')"
typescript_decl_lines="$(sum_lines _build '*.d.ts')"
javascript_lines="$(sum_lines _build '*.js')"
diagnostic_files="$(find _build -path "$report_root" -prune -o -type f \( -name 'SCAFFOLD_DIAGNOSTICS.md' -o -name 'AUTOLINK_DIAGNOSTICS.md' \) -print | wc -l | tr -d ' ')"
unsupported_exports="$(count_matching_files _build 'bridge.mbti' '^/// Unsupported export ')"
moonbit_declared_functions="$(count_matching_files _build 'bridge.mbti' '^declare pub fn ')"
moonbit_declared_types="$(count_matching_files _build 'bridge.mbti' '^declare pub type ')"
typescript_exported_declarations="$(count_matching_files _build '*.d.ts' '^export (declare )?(function|interface|class|const|type) ')"
jsvalue_refs="$(count_matching_files _build 'bridge.mbti' 'JSValue')"
jsvalue_functions="$(count_matching_files _build 'bridge.mbti' '^declare pub fn .*JSValue')"
moon_build_smokes="$(find _build -path "$report_root" -prune -o -type d -name '__tsmbt_build_smoke__' -print | wc -l | tr -d ' ')"

overall="pass"
for status in "${statuses[@]}"; do
  if [ "$status" != "pass" ]; then
    overall="fail"
  fi
done

{
  printf '# Bridge Quality Report\n\n'
  printf 'Generated by `scripts/bridge_quality_report.sh`.\n\n'
  printf 'Overall: `%s`\n\n' "$overall"
  printf '## Verification Summary\n\n'
  printf '| check | status | log |\n'
  printf '| --- | --- | --- |\n'
  for i in "${!checks[@]}"; do
    printf '| %s | %s | `%s` |\n' "${checks[$i]}" "${statuses[$i]}" "${logs[$i]}"
  done
  printf '\n'
  printf '## Generated Artifact Metrics\n\n'
  printf '| metric | value |\n'
  printf '| --- | ---: |\n'
  printf '| MoonBit bridge implementations | %s |\n' "$moonbit_bridge_files"
  printf '| MoonBit bridge interfaces | %s |\n' "$moonbit_decl_files"
  printf '| TypeScript declarations | %s |\n' "$typescript_decl_files"
  printf '| JavaScript files | %s |\n' "$javascript_files"
  printf '| MoonBit bridge implementation lines | %s |\n' "$moonbit_bridge_lines"
  printf '| MoonBit bridge interface lines | %s |\n' "$moonbit_decl_lines"
  printf '| TypeScript declaration lines | %s |\n' "$typescript_decl_lines"
  printf '| JavaScript lines | %s |\n' "$javascript_lines"
  printf '| MoonBit declared functions | %s |\n' "$moonbit_declared_functions"
  printf '| MoonBit declared types | %s |\n' "$moonbit_declared_types"
  printf '| TypeScript exported declarations | %s |\n' "$typescript_exported_declarations"
  printf '| diagnostics files | %s |\n' "$diagnostic_files"
  printf '| unsupported exports | %s |\n' "$unsupported_exports"
  printf '| JSValue refs | %s |\n' "$jsvalue_refs"
  printf '| JSValue functions | %s |\n' "$jsvalue_functions"
  printf '| generated build-smoke packages | %s |\n' "$moon_build_smokes"
} > "$report_file"

cat "$report_file"

if [ "$overall" != "pass" ]; then
  exit 1
fi
