#!/usr/bin/env bash
# Regenerate src/checker/lib_globals.mbt from the TypeScript standard library
# declaration files (typescript/src/lib/*.d.ts in the submodule).
#
# The output bakes the *names* of every ambient global value and type the
# standard libraries declare into two predicate functions, so the checker can
# treat references to them as resolved (rather than emitting TS2304 "Cannot
# find name" / unresolved-type-reference diagnostics). The union across every
# lib target is intentional: a larger allowlist only ever suppresses a
# diagnostic, never causes a false positive.
#
# Requires the populated `typescript` submodule. Commit the generated file —
# the main CI job does not check out the submodule.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
LIB="$ROOT/typescript/src/lib"
OUT="$ROOT/src/checker/lib_globals.mbt"

if [ ! -d "$LIB" ]; then
  echo "lib sources not found at $LIB (populate the typescript submodule)" >&2
  exit 1
fi

# Ambient global *values*: declare var/let/const/function/class/namespace/enum.
# Node / CommonJS additions (not in the DOM/ES libs) are appended manually.
{
  grep -hoP '^\s*declare\s+(?:var|let|const|function|async function|class|abstract class|namespace|enum)\s+\K[A-Za-z_$][A-Za-z0-9_$]*' "$LIB"/*.d.ts || true
  printf '%s\n' globalThis process Buffer require module exports global \
    __dirname __filename setImmediate clearImmediate gc
} | sort -u > /tmp/lib_value_names.txt

# Ambient global *types*: interface / type alias / declare class / namespace / enum.
# `declare type X = ...` (lib.es5's PropertyKey, the *Decorator aliases,
# PromiseConstructorLike) needs its own alternative — the bare `type` branch
# only matches un-prefixed aliases.
grep -hoP '^\s*(?:interface|type|declare\s+(?:class|abstract class|namespace|enum|type))\s+\K[A-Za-z_$][A-Za-z0-9_$]*' "$LIB"/*.d.ts \
  | sort -u > /tmp/lib_type_names.txt

emit_match() {
  # $1 = fn name, $2 = names file. Emits a single match arm of the form
  #   "a" | "b" | ... => true
  # wrapped across lines; continuation lines start with "| " so adjacent
  # lines join into one alternation without producing an empty alternative.
  echo "fn $1(name : String) -> Bool {"
  echo "  match name {"
  awk '{ printf "\"%s\"", $0; if (NR % 6 == 0) printf "\n" ; else printf " " }
       END { if (NR % 6 != 0) printf "\n" }' "$2" \
    | sed 's/" "/" | "/g' \
    | sed '1 s/^/    /; 2,$ s/^/    | /'
  echo "    => true"
  echo "    _ => false"
  echo "  }"
  echo "}"
}

{
  echo "// @generated by scripts/gen_lib_globals.sh — do not edit by hand."
  echo "// Names of ambient global values / types declared by the TypeScript"
  echo "// standard libraries (typescript/src/lib/*.d.ts), unioned across every"
  echo "// target. Used by the checker to resolve references to standard globals."
  echo ""
  echo "///|"
  echo "/// True when \`name\` is a standard-library ambient global *value*"
  echo "/// (\`console\`, \`Math\`, \`Promise\`, \`document\`, \`Symbol\`, …)."
  emit_match is_lib_global_value /tmp/lib_value_names.txt
  echo ""
  echo "///|"
  echo "/// True when \`name\` is a standard-library ambient global *type*"
  echo "/// (\`PropertyDescriptor\`, \`PromiseLike\`, \`HTMLElement\`,"
  echo "/// \`IteratorResult\`, …). Interfaces, type aliases, declared classes,"
  echo "/// namespaces, and enums across every lib target."
  emit_match is_lib_global_type /tmp/lib_type_names.txt
} > "$OUT"

echo "wrote $OUT"
echo "  value globals: $(wc -l < /tmp/lib_value_names.txt)"
echo "  type globals:  $(wc -l < /tmp/lib_type_names.txt)"
